timeout: 300s
steps:
  - name: 'maven:3.8.1-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-sprint-boot-repo2506', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-sprint-boot-repo2506']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-sprint-boot-repo2506'
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-sprint-boot-repo2506'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY